### ISSUE TITLE
None of the Proposed or the 2 DeepLab based methods train successfully

### ISSUE THREAD

**Issue by vladtimug** [RadekZenkl/EWS#1]
Hi, I am trying to reproduce the results you achieved but none of the above mentioned methods seem to be able to train successfully. So far I can only tell that for each of the approaches the training stops soon after it starts. What I mean by that is that the script `main.py` or any of the related ones do no throw any error but the training procedure gets stuck and just stays there. I've also checked in parallel what is the load on the GPU while training and indeed when the training information in the console stops updating the load on the GPU drops to 0%. Do you have any hints as to why this might occur?
I'm using an Nvidia RTX Quadro 6000 for training and the conda environment used to run this was created as per the provided `env.yaml` file in the repo.

**Comment by RadekZenkl** [comment]
Hey, 
I would suspect differences in Hardware causing this. First thing that I would investigate is, whether you are able to utilize the GPU from within pytorch. Try executing this and please post the response:

```
import torch
print(torch.zeros(1).cuda())
```

I believe that RTX Quadro 6000 might need different cuda tool kit than RTX 3070 which we used. 

If your GPU can be utilized, then I would investigate the number of threads. By default the code spawns 8 workers to preload data, while the GPU is still computing. Do you have so many cores resp. threads available?

You wrote that the GPU utilization drops back to 0. Does this mean, that there was some utilization before?

**Comment by vladtimug** [comment]
Hey,
Yes, the GPU is available for utilization from pytorch. I tried running with 4 and 16 threads as well but the behavior was the same. It stopped a little earlier when spawning 4 threads for data loading than it did with the 8 or 16 threads. I also did one test with num_workers=1 and that was the one that got the farthest into the training procedure but then it stopped later on.
Yes, initially the model starts training and somewhere along the row before the 20th epoch just stops and the GPU load drops from whatever value it has at that time to 0 and then it just stays there.

LE: I figured it is able to completely train if I set the num_workers to 0. However I'm not sure I understand why that is the case. Any insight on this would be helpful.

**Comment by RadekZenkl** [comment]
Hi, 

This is indeed very odd behavior. Another possibility is that this behavior is caused by computing the metrics. In order to be consistent with the other methods, the used metrics are from sklearn. This means however, that their implementation is on the CPU. This would explain why the GPU utilization drops back to 0 after some time. If the trigger is always  "somewhere along the row before the 20th epoch"  this might explain it. 

If setting num_workers to 0 helps this would indicate that when new computations arrive (possibly metrics computations threads are spawned), the code deadlocks itself. But if the code runs single threaded then this lock does not happen. 
Relevant reading: https://pytorch.org/docs/stable/data.html

I will try to test this on different hardware to see if I can reproduce your issue. 
Is training with num_workers=0 (single threaded) an option for you?

**Comment by vladtimug** [comment]
Hi,

Currently, with the hardware I have available I can manage to work with num_workers=0. However I would like to understand why that behavior is occurring. Thanks for your implication.

**Comment by RadekZenkl** [comment]
Hey @vladtimug 
Sorry for the late response. I have tested the code on another machine and it worked for me. Maybe it is a hardware or drivers specific issue? 

For comparison the tested machines run:
RTX3070, AMD Ryzen Threadripper 3960X, Fedora 
and
RTX3060ti, AMD Ryzen 5900x, Ubuntu

I am sorry, that I cannot reproduce the issue. Does it occur to you every single time?

**Comment by vladtimug** [comment]
Hey @RadekZenkl,

It used to happen every single time yes. I haven't had that much time on my hands to look further into it after I trained it with num_workers=0.
It's fine if you can't reproduce it, don't worry about it. I appreciate the effort anyways.
